name: Build Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to build'
        required: true
        default: 'v1.0.0-stable'
      
jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.2.2
    
    - name: Set up Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.12.3'
        cache: 'pip'
        architecture: 'x64'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Executable
      shell: cmd
      run: |
        set TAG=${{ github.event.inputs.version }}
        pyinstaller --onefile --name SignalCrypt-%TAG% main.py
    
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        tag: ${{ github.event.inputs.version }}
        artifacts: "dist/SignalCrypt-${{ github.event.inputs.version }}.exe"
        body: ${{ contains(github.event.inputs.version, '-stable') && 'Stable Release' || 'Beta Release | Bugs might occur, please report them as an Issue.' }}
        prerelease: ${{ or(contains(github.event.inputs.version, '-alpha'), contains(github.event.inputs.version, '-beta')) }}
